# Site Settings
title:               nibbly.io
tagline:             How we made an IO game
description:
baseurl:            #
url:                "http://blog.nibbly.io"
github:
  url:               "http://blog.nibbly.io"
author:
  name:              "Polplay Studios Incorporated"
  email:
  twitter:
  instagram:
  github:
  facebook:
  linkedin:
navigation:
- title: #About
  url: #/about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
